import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  rect: {
    width: 187,
    height: 200,
    backgroundColor: "#7c7bad",
    borderRadius: 50,
    marginTop: 20,
    alignSelf: "center",
  },
  image: {
    height: 150,
    width: 150,
    marginTop: 23,
    marginLeft: 19,
    borderRadius: 35,
  },
  rect4: {
    width: 327,
    height: 388,
    backgroundColor: "rgba(230,230,230,0.16)",
    marginTop: 5,
    marginLeft: 17,
  },
  profileName: {
    //fontFamily: "calibri-bold",
    color: "#121212",
    height: 51,
    width: 243,
    textAlign: "center",
    fontSize: 30,
    marginTop: 21,
    marginLeft: 42,
  },
  rect3: {
    width: 325,
    height: 43,
    backgroundColor: "#E6E6E6",
    flexDirection: "row",
    marginTop: 11,
    marginLeft: 1,
  },
  icon: {
    color: "#7c7bad",
    fontSize: 30,
    height: 34,
    width: 25,
  },
  email2: {
    //fontFamily: "roboto-regular",
    color: "#121212",
    height: 28,
    width: 268,
    marginLeft: 16,
    marginTop: 6,
  },
  iconRow: {
    height: 34,
    flexDirection: "row",
    flex: 1,
    marginRight: 8,
    marginLeft: 8,
    marginTop: 1,
  },
  rect7: {
    width: 325,
    height: 43,
    backgroundColor: "#E6E6E6",
    flexDirection: "row",
    marginTop: 6,
    marginLeft: 1,
  },
  icon5: {
    color: "#7c7bad",
    fontSize: 30,
    height: 34,
    width: 13,
  },
  phone: {
    //fontFamily: "roboto-regular",
    color: "#121212",
    height: 28,
    width: 268,
    marginLeft: 23,
    marginTop: 6,
  },
  icon5Row: {
    height: 34,
    flexDirection: "row",
    flex: 1,
    marginRight: 8,
    marginLeft: 13,
    marginTop: 2,
  },
  rect5: {
    width: 325,
    height: 43,
    backgroundColor: "#E6E6E6",
    flexDirection: "row",
    marginTop: 6,
    marginLeft: 1,
  },
  icon3: {
    color: "#7c7bad",
    fontSize: 30,
    height: 34,
    width: 18,
  },
  street: {
    //fontFamily: "roboto-regular",
    color: "#121212",
    height: 28,
    width: 268,
    marginLeft: 20,
    marginTop: 7,
  },
  icon3Row: {
    height: 35,
    flexDirection: "row",
    flex: 1,
    marginRight: 8,
    marginLeft: 11,
    marginTop: 1,
  },
  rect6: {
    width: 325,
    height: 43,
    backgroundColor: "#E6E6E6",
    flexDirection: "row",
    marginTop: 8,
    marginLeft: 1,
  },
  icon4: {
    color: "#7c7bad",
    fontSize: 30,
    height: 34,
    width: 22,
  },
  country: {
    //fontFamily: "roboto-regular",
    color: "#121212",
    height: 28,
    width: 268,
    marginLeft: 18,
    marginTop: 6,
  },
  icon4Row: {
    height: 34,
    flexDirection: "row",
    flex: 1,
    marginRight: 8,
    marginLeft: 9,
    marginTop: 1,
  },
  button: {
    width: 327,
    height: 37,
    backgroundColor: "#7c7bad",
    marginTop: 45,
  },
  logOut: {
    //fontFamily: "roboto-700",
    color: "#121212",
    fontSize: 20,
    textAlign: "center",
    marginTop: 8,
    //marginLeft: 122,
  },
});
export default styles;
